#!/bin/bash
set -e

# kill background jobs when done
trap 'kill $(jobs -pr)' SIGINT SIGTERM EXIT

# env vars
export DATABASE_URL=${DATABASE_URL:-postgres://localhost/scribly}
export SCRIBLY_PORT=8000
export MOCK_SENDGRID_PORT=9991
export SENDGRID_BASE_URL="http://127.0.0.1:$MOCK_SENDGRID_PORT"
export WEBSITE_URL="http://127.0.0.1:$SCRIBLY_PORT"

# reset database
python scripts/createdb.py --reset

# start mock servers
docker run --rm -p $MOCK_SENDGRID_PORT:1080 mockserver/mockserver &

# start app
heroku local -p $SCRIBLY_PORT
